### ISSUE TITLE
Export and Import of Model Version Activity

### ISSUE THREAD

**Issue by sdeepak09** [mlflow/mlflow-export-import#132]
I have used this package for migration of MlFlow models and experiment from one instance of databricks to another. In this process I was not able to get anything around around exporting and importing of Model Version activities, can anyone suggest if this can be achieved?

**Comment by amesar** [comment]
Haven't had any problems with importing Model Versions. What is a "Model Version activities"? Check your exported model.json file for model versions.

**Comment by sdeepak09** [comment]
> Haven't had any problems with importing Model Versions. What is a "Model Version activities"? Check your exported model.json file for model versions.

Sorry for the delayed response, somehow I missed your reply. By "Model Version activities" I mean, activities related to model's movement from and to staging/production/archive. So, I wanted to import the comments which we provide while moving a model from one stage to another. Hope this helps.
