### ISSUE TITLE
How to use GCP credentials for access to bucket?

### ISSUE THREAD

**Issue by Yevhesha95** [mlflow/mlflow-export-import#137]
Hello team.

I facing with problem after run export-model command.
I understand that it cannot access the bucket to pull out the data.
Right?
How can I solve the problem?
____________________________________________________________________________________________________________

export-model --model demo --output-dir ./out

28-Jul-23 06:33:42 - INFO - Using default logging config without output log file
28-Jul-23 06:33:42 - INFO - Options:
28-Jul-23 06:33:42 - INFO -   model: demo
28-Jul-23 06:33:42 - INFO -   output_dir: ./out
28-Jul-23 06:33:42 - INFO -   stages: None
28-Jul-23 06:33:42 - INFO -   versions: None
28-Jul-23 06:33:42 - INFO -   export_latest_versions: False
28-Jul-23 06:33:42 - INFO -   export_deleted_runs: False
28-Jul-23 06:33:42 - INFO -   export_version_model: False
28-Jul-23 06:33:42 - INFO -   export_permissions: False
28-Jul-23 06:33:42 - INFO -   notebook_formats:
28-Jul-23 06:33:42 - INFO - Exporting model 'demo': found 1 'all' versions
28-Jul-23 06:33:42 - INFO - Exporting model verson 1/1: {'name': 'demo', 'version': '1', 'stage': 'None'} to './out/a9b0ab2f674948be9da5d786b9d76896'
28-Jul-23 06:33:43 - INFO - Exporting run: {'run_id': 'a9b0ab2f674948be9da5d786b9d76896', 'lifecycle_stage': 'active', 'experiment_id': '19'}
28-Jul-23 06:33:48 - DEBUG - Checking None for explicit credentials as part of auth process...
28-Jul-23 06:33:48 - DEBUG - Checking Cloud SDK credentials as part of auth process...
28-Jul-23 06:33:49 - DEBUG - Checking None for explicit credentials as part of auth process...
28-Jul-23 06:33:49 - DEBUG - Checking Cloud SDK credentials as part of auth process...
28-Jul-23 06:33:50 - DEBUG - Making request: POST https://oauth2.googleapis.com/token
28-Jul-23 06:33:52 - DEBUG - Checking None for explicit credentials as part of auth process...
28-Jul-23 06:33:52 - DEBUG - Checking Cloud SDK credentials as part of auth process...
28-Jul-23 06:33:53 - DEBUG - Checking None for explicit credentials as part of auth process...
28-Jul-23 06:33:53 - DEBUG - Checking Cloud SDK credentials as part of auth process...
28-Jul-23 06:33:54 - DEBUG - Making request: POST https://oauth2.googleapis.com/token

(it freezes and nothing happens)
____________________________________________________________________________________________________________________

I used "gcloud auth login" for login to project and set as default my project and region.
I have Admin permissions to bucket and K8s.

Version:
pip 23.2.1 from ****/.local/lib/python3.8/site-packages/pip (python 3.8)

Please, write if you need more info from me.

**Comment by amesar** [comment]
Bucket permission issues are outside the scope of the mlflow-export-import tool.

**Comment by rafaeljcdarce** [comment]
@Yevhesha95 did you find a solution to this?
