### ISSUE TITLE
Machine learning artifacts export support

### ISSUE THREAD

**Issue by WAG10** [mlflow/mlflow-export-import#140]
Hi Team,
While using the utility we see only export of **experiments and models** getting supported. Other ML leaning artifacts **'Features' and 'servings'** are not getting exported.
Requesting your kind confirmation on this that these are not being supported or if affirmative that they support, your kind guidance on how to use this utility for exporting them

**Comment by amesar** [comment]
The tool handles MLflow objects supported by the open source MLflow API. "Features" and "servings" are not part of MLflow.
