### ISSUE TITLE
Runs imported but models not after using import-models

### ISSUE THREAD

**Issue by jswtraveler** [mlflow/mlflow-export-import#42]
Hi, thank you so much for developing this package. I am trying to migrate experiments, runs, and models from our old mlflow server to our new one. I exported the models using `export-models --output-dir mlflow_model_output_dir2 --models shortage_lgb_resource_count_3dp_all_21mth,shortage_lgb_open_duty_ct_3dp_all_21mth --export-source-tags True --export-all-runs True` sucessfully. I then changed the mlflow uri to our new location and used import-models. The experiment and runs are all imported and when looking at the model registry the model names are both there. However, under the registry/model name there are no versions. In the experiment UI window there are no links to models, but I can find the artifacts along with the "register model" button if I click through the runs into a single runs details. I have attached screenshots of the original model registry for the model I am moving, the new model registry, and the output of the import-models run.
<img width="1669" alt="original_mlflow_server_model_registry" src="https://user-images.githubusercontent.com/40544835/196252559-f3f1f401-2683-4fea-b192-5836108a6cbe.png">
<img width="1669" alt="new_mlflow_server_model_registry" src="https://user-images.githubusercontent.com/40544835/196252565-1743c92f-6d67-4843-9c32-1d464aad6380.png">
<img width="559" alt="terminal_import_model_finished_" src="https://user-images.githubusercontent.com/40544835/196252566-e9610190-024d-4ff7-8e99-10a27063197c.png">

**Comment by jswtraveler** [comment]
Apologies for what might be a basic question. Is there a way to send them without making them publicly available on the issues page?

**Comment by jswtraveler** [comment]
> I'd need for info. Can you send a zipped of the exported model directory?
Apologies for what might be a basic question. Is there a way to send them without making them publicly available on the issues page?

**Comment by jswtraveler** [comment]
[export_models_single_ex.zip](https://github.com/mlflow/mlflow-export-import/files/10006678/export_models_single_ex.zip)
Hi, so so so sorry for the late reply. I've attached a zip file that has the output. It's a large model so I deleted all but a single run with the artifacts etc but the file structure etc is what the export-models output created.

**Comment by amesar** [comment]
The zip file contains the output of export-experiments and not export-models. The one experiment was successfully imported.

**Comment by jswtraveler** [comment]
Apologies, I didn't compress the model folder as well for some reason. I've attached the correct compressed folder this time. I dropped all but one of the run folders like before because of file size of attachments. I've also attached the terminal screenshot that created the folder that I then compressed. Thank you again so much for your help.
![export-models-terminal-screenshot](https://user-images.githubusercontent.com/40544835/202735166-cbda4a70-43a3-47b6-96bd-73b57b8dcca3.png)
[sdr_export_model_example.zip](https://github.com/mlflow/mlflow-export-import/files/10042341/sdr_export_model_example.zip)

**Comment by amesar** [comment]
I have successfully imported the zip file. I don't see any issues. 

If you manually delete runs from an experiment in the export directory, you have to adjust the experiment sdr_export_model_example/experiments/304/manifest.json file and adjust export_info.ok_runs otherwise import will fail.

**Comment by jswtraveler** [comment]
The deletions were only for uploading to git since the total file size was ~250mb due to artifacts. When I try to use import-models for the original folder without any deletions it imports the experiment, runs, and artifacts but doesn't register the model or any of the versions. But it sounds like you don't see anything wrong with the exported folder structure. I made a workaround to migrate manually in a loop just calling the original server to get each model version then manually registering/re-saving the model versions to the new directory. Thank you for your help.

**Comment by amesar** [comment]
Cool. I'll close the ticket.
