### ISSUE TITLE
Exporting artifacts of a specific version of a model

### ISSUE THREAD

**Issue by SDonkelaarGDD** [mlflow/mlflow-export-import#50]
Hi,

We would like to export the artifacts of a _specific_ version of a model. 

Unfortunately, it seems that this is not possible: the function `export_model` from the `ModelExporter` class first fetches all versions, and then iteratively exports the artifacts of each model version. However, we often only need to export a specific model version. Moreover, since our artifacts can become quite big, and each model can have a lot of versions, it can take a lot of time (and storage) to first export all models, only to migrate a specific version.

Is this functionality currently on the roadmap? Otherwise I'm happy to contribute .

**Comment by amesar** [comment]
[export-model ](https://github.com/mlflow/mlflow-export-import/blob/master/README_individual.md#Export-Registered-model) can already filter by stage. Is that good enough?

```
export-model --help

Options:
  --model TEXT       Registered model name.  [required]
  --output-dir TEXT  Output directory.  [required]
  --export-source-tagss BOOLEAN  Export source run information (RunInfo,
                                 MLflow system tags starting with 'mlflow' and
                                 metadata) under the 'mlflow_export_import'
                                 tag prefix. See README.md for more details.
                                 [default: False]
  --notebook-formats TEXT         Notebook formats. Values are SOURCE, HTML,
                                  JUPYTER or DBC (comma seperated).  [default: ]
                                  True]
  --stages TEXT                   Stages to export (comma seperated). Default
                                  is all stages. Values are Production,
                                  Staging, Archived and None
```

**Comment by SDonkelaarGDD** [comment]
@amesar yes, I saw that. Filtering for the stage would be possible in our use-case, but sub-optimal. A more preferred way would be to export on version.

**Comment by amesar** [comment]
OK, I'll look into it.

**Comment by amesar** [comment]
Note that there is no guarantee that the imported versions will have the same version number as the exported versions. If you export version 1 and 2, you will get version 1 and 2 in the destination tracking server. However, if the source server has model versions 1,2,3 and 4, and you export 2 and 4, your imported destination versions will be 1 and 2. The version ID is a monotonically increasing integer generated by the system, and there is no way for the client to set its value.

Let me know if this is OK so I can proceed.

See also: https://github.com/mlflow/mlflow-export-import/issues/41 - Version Sequence: Sort version sequence in the export log

**Comment by SDonkelaarGDD** [comment]
Yes I'm aware. It's a bit inconvenient. Still, it would be a very nice functionality to have for us.

**Comment by amesar** [comment]
OK.

**Comment by SDonkelaarGDD** [comment]
Thanks a lot!
