### ISSUE TITLE
Mlflow host or token is not configured correctly (Open-source)

### ISSUE THREAD

**Issue by vincentvic** [mlflow/mlflow-export-import#56]
Hi !
I'am wondering if i's possible to export/import mlflow (experiement, run, model, etc) with a MLflow with remote Tracking Server, backend and artifact stores. So without using Databricks.
If it's the case I have this error "Mlflow host or token is not configured correctly (Open-source)".
Someone can help me ? Thank you
Victor,

**Comment by amesar** [comment]
The tool works for both OSS and Databricks tracking servers. Make sure DATABRICKS_TOKEN is not set. When exporting, set MLFLOW_TRACKING_URI to your source tracking server. When importing, set MLFLOW_TRACKING_URI to your destination tracking server
