### ISSUE TITLE
`import-experiments` destroy the time information, making the tool useless

### ISSUE THREAD

**Issue by fzyzcjy** [mlflow/mlflow-export-import#59]
Originally it was like the following (on a file system store)

![image](https://user-images.githubusercontent.com/5236035/206707908-215324a0-83f4-4128-8911-a8bb3820b1c6.png)

But after export and import, it becomes this, i.e. all time information is destroyed!

![image](https://user-images.githubusercontent.com/5236035/206707973-ce6fd0ba-22fb-4d27-b0ca-550f38210662.png)

**Comment by amesar** [comment]
There is not enough information to make a diagnosis. It isn't clear what "time information" refers to. Duration column? I see it in both screen shots. Have you looked in the JSON files to see the value of the Duration field?

Note the the exporting/importing from file store which is not production quality - is not supported. See: [General Limitations](https://github.com/mlflow/mlflow-export-import/blob/master/README.md#general-limitations)

**Comment by fzyzcjy** [comment]
anyway I have solved it: https://github.com/fzyzcjy/mlflow-export-import
