### ISSUE TITLE
make tool compatible on python 3.6

### ISSUE THREAD

**Issue by PaulZhangIsing** [mlflow/mlflow-export-import#82]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **MLflow installed from (source or binary)**: From github + self customization
- **MLflow version (run ``mlflow --version``)**: mlflow 1.29.0
- **Python version**: 3.6

I would like to know the requirements /  codes I need to modify if I want to make the mlflow running in python3.6 version. Currently most of my projects depending on python3.6, therefore I would like to do something about it.

I know from setup config there are plenty of things I need to change, besides them, i could do 
```
pip install -e.
```
However, by the time I try to trigger 

```
export-experiments
```
it shall give me importlib.metadata problem

Anything I could do to fix it?

**Comment by amesar** [comment]
Python 3.6 is end-of-life on 2021-12-23. I would recommend upgrading to current version of Python.
