### ISSUE TITLE
host_name variable definition results in py4j error

### ISSUE THREAD

**Issue by badjouras** [mlflow/mlflow-export-import#97]
Running the `%run ./Common` cell in a databricks_notebooks/single notebook results in a py4 error:

> py4j.security.Py4JSecurityException: Method public scala.collection.immutable.Map com.databricks.backend.common.rpc.CommandContext.tags() is not whitelisted on class class com.databricks.backend.common.rpc.CommandContext

The error happens when the host_name definition line is run:

> Py4JError                                 Traceback (most recent call last)
> File <command-2057775582524418>:1
> ----> 1 host_name = dbutils.notebook.entry_point.getDbutils().notebook().getContext().tags().get("browserHostName")

**Comment by amesar** [comment]
Pushed fixes. Try downloading notebooks again.

https://github.com/mlflow/mlflow-export-import/issues/98
